### ISSUE TITLE
Remote debugging breaks but does not enter the debugger

### ISSUE THREAD

**Issue by surfer190** [sassoftware/epdb#12]
I am trying to debug an ansible module.
I run the playbook and then connect:

```
$ python3.6 -c 'import epdb; epdb.connect()'
> /Users/stephen/test/provisioning_ansible/env/lib/python3.8/site-packages/pyvcloud/vcd/vdc.py(2056)create_gateway_api_version_31()
-> gateway_params = E.EdgeGateway(name=name)
n
c
s
```

As you can see it never enters `(Epdb)`

When I `C-c` (Ctrl-c) the following error is show:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/epdb/__init__.py", line 1091, in connect
    t.interact()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/epdb/epdb_client.py", line 117, in interact
    neededWriters, [])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/epdb/epdb_client.py", line 82, in ctrl_c
    self.sock.sendall('close\n')
TypeError: a bytes-like object is required, not 'str'
```

Is there something I need to do extra?

**Comment by wfscheper** [comment]
I wasn't able to reproduce the lack of output or `(Epdb)` prompt; that may be something ansible is doing to the terminal. However, I was able to reproduce the Traceback with a very simple script:

```python
import sys


def main():
    import epdb

    epdb.serve()

    print("hello world")


if __name__ == "__main__":
    sys.exit(main())
```

```shell
$ python3 -c 'import epdb; epdb.connect()'
*** NameError: name 'execfile' is not defined
> /Users/wasche/tmp/test.py(9)main()
-> print("hello world")
(Epdb) n
hello world
--Return--
> /Users/wasche/tmp/test.py(9)main()->None
-> print("hello world")
(Epdb) c
hello world
<I typed CTRL-C here>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/wasche/.virtualenvs/epdb-test/lib/python3.6/site-packages/epdb/__init__.py", line 1091, in connect
    t.interact()
  File "/Users/wasche/.virtualenvs/epdb-test/lib/python3.6/site-packages/epdb/epdb_client.py", line 117, in interact
    neededWriters, [])
  File "/Users/wasche/.virtualenvs/epdb-test/lib/python3.6/site-packages/epdb/epdb_client.py", line 82, in ctrl_c
    self.sock.sendall('close\n')
TypeError: a bytes-like object is required, not 'str'
```

Pretty clearly we missed this when we did the python3 conversion.

**Comment by wfscheper** [comment]
Okay, this is fixed, but unreleased.

I'll start working on cutting a patch release.

**Comment by surfer190** [comment]
Thanks @wfscheper should I use the git commit sha1 in the meantime to download with pip?
